version: '3.3'

services:

  elasticsearch:
    build:
      context: config/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  kibana:
    build:
      context: config/kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: config/logstash
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk: